version: '3'
services:
  jaeger:
    image: "jaegertracing/all-in-one:1.11"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "16686:16686"
  api:
    build:
      dockerfile: api/Dockerfile
      context: .
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
  report-generator:
    build:
      dockerfile: report-generator/Dockerfile
      context: .
    restart: always
    deploy:
      mode: replicated
      replicas: 4